### ISSUE TITLE
pymysql packet sequence errors

### ISSUE THREAD

**Issue by ledlamp** [osuAkatsuki/gulag#129]
it seems whenever connecting to the server after a while of inactivity, the osu bansho connection takes a long time (like half to one minute) and there's this error printed to console

![](https://2rkr.owo69.me)

**Comment by ledlamp** [comment]
maybe caused by memory swap?

**Comment by cmyui** [comment]
These should all be resolved now, it was an issue with using the asynchronous coroutines in aiomysql (`conn.iterate` methods), which I believe may have a concurrency bug.
