### ISSUE TITLE
Group by query fails in /api/get_player_most_played

### ISSUE THREAD

**Issue by def750** [osuAkatsuki/gulag#171]
I have weird error on API route `/get_player_most_played`
After update it stopped working, there are no changes from me. Also I think that route for getting recent scores doesn't work too.

`pymysql.err.InternalError: (1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'gulag.m.md5' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")`
https://pastebin.com/qaNVy3LV

**Comment by cmyui** [comment]
@def750 ideally each of those points should become an individual github issue; since they're all issues with gulag.

1 github issue = 1 gulag issue

**Comment by def750** [comment]
Okay. I've also checked above issues with fresh and empty database. Still not not working so it's not an issue with my db.

**Comment by def750** [comment]
Nevermind. I have the problem now I guess. It's working with empty database.

**Comment by def750** [comment]
Yeah, It's fine with fresh database. I have some issues with mine I guess.

**Comment by cmyui** [comment]
@def750 are *all* of these bugs reported here fixed with a fresh db?

**Comment by def750** [comment]
Yeah. I'm trying to figure out what happened with the database because it wasn't changed in any way. I compared both fresh and our db and it was exact same.
